---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-oci-oci-v1beta1-autonomousdatabases
  failurePolicy: Ignore
  name: mautonomousdatabases.kb.io
  rules:
  - apiGroups:
    - oci.oracle.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-oci-oci-v1beta1-nosqldatabase
  failurePolicy: Ignore
  name: mnosqldatabase.kb.io
  rules:
  - apiGroups:
    - oci.oracle.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nosqldatabases
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-oci-oci-v1beta1-autonomousdatabases
  failurePolicy: Fail
  name: vautonomousdatabases.kb.io
  rules:
  - apiGroups:
    - oci.oracle.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomousdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-oci-oci-v1beta1-nosqldatabase
  failurePolicy: Fail
  name: vnosqldatabase.kb.io
  rules:
  - apiGroups:
    - oci.oracle.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nosqldatabases
  sideEffects: None
