#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

# permissions for end users to view containerinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerinstance-viewer-role
rules:
- apiGroups:
  - oci.oracle.com
  resources:
  - containerinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oci.oracle.com
  resources:
  - containerinstances/status
  verbs:
  - get
