#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

# permissions for end users to edit containerinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerinstance-editor-role
rules:
- apiGroups:
  - oci.oracle.com
  resources:
  - containerinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oci.oracle.com
  resources:
  - containerinstances/status
  verbs:
  - get
