---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rediscluster-viewer-role
rules:
- apiGroups:
  - oci.oracle.com
  resources:
  - redisclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oci.oracle.com
  resources:
  - redisclusters/status
  verbs:
  - get
