---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oci.oracle.com
  resources:
  - apigatewaydeployments
  - apigateways
  - autonomousdatabases
  - devopsprojects
  - functionsapplications
  - functionsfunctions
  - mysqldbsystems
  - containerinstances
  - nosqldatabases
  - ociqueues
  - opensearchclusters
  - redisclusters
  - streams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oci.oracle.com
  resources:
  - apigatewaydeployments/finalizers
  - apigateways/finalizers
  - autonomousdatabases/finalizers
  - containerinstances/finalizers
  - devopsprojects/finalizers
  - functionsapplications/finalizers
  - functionsfunctions/finalizers
  - mysqldbsystems/finalizers
  - nosqldatabases/finalizers
  - ociqueues/finalizers
  - opensearchclusters/finalizers
  - redisclusters/finalizers
  - streams/finalizers
  verbs:
  - update
- apiGroups:
  - oci.oracle.com
  resources:
  - apigatewaydeployments/status
  - apigateways/status
  - autonomousdatabases/status
  - containerinstances/status
  - devopsprojects/status
  - functionsapplications/status
  - functionsfunctions/status
  - mysqldbsystems/status
  - nosqldatabases/status
  - ociqueues/status
  - opensearchclusters/status
  - redisclusters/status
  - streams/status
  verbs:
  - get
  - patch
  - update
