#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: oci.oracle.com/v1beta1
kind: OciVault
metadata:
  name: sample-vault
spec:
  compartmentId: ocid1.compartment.oc1..aaaaaaaaXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  displayName: SampleVault
  vaultType: DEFAULT
  # id: ocid1.vault.oc1.<region_code>.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  # bind to existing vault
  # key:
  #   displayName: SampleKey
  #   keyShape:
  #     algorithm: AES
  #     length: 32
