#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: oci.oracle.com/v1beta1
kind: OpenSearchCluster
metadata:
  name: opensearchcluster-sample
spec:
  compartmentId: ocid1.compartment.oc1..aaaaaaaaXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  displayName: SampleOpenSearchCluster
  softwareVersion: "2.11.0"

  masterNodeCount: 3
  masterNodeHostType: FLEX
  masterNodeHostOcpuCount: 2
  masterNodeHostMemoryGB: 16

  dataNodeCount: 3
  dataNodeHostType: FLEX
  dataNodeHostOcpuCount: 4
  dataNodeHostMemoryGB: 32
  dataNodeStorageGB: 100

  opendashboardNodeCount: 1
  opendashboardNodeHostOcpuCount: 2
  opendashboardNodeHostMemoryGB: 8

  vcnId: ocid1.vcn.oc1.<region-short-code>.aaaaaaaaXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  subnetId: ocid1.subnet.oc1.<region-short-code>.aaaaaaaaXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  vcnCompartmentId: ocid1.compartment.oc1..aaaaaaaaXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  subnetCompartmentId: ocid1.compartment.oc1..aaaaaaaaXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  securityMode: PERMISSIVE
