---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.0
  name: ocisecuritylists.oci.oracle.com
spec:
  group: oci.oracle.com
  names:
    kind: OciSecurityList
    listKind: OciSecurityListList
    plural: ocisecuritylists
    singular: ocisecuritylist
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.displayName
      name: DisplayName
      priority: 1
      type: string
    - description: status of the OciSecurityList
      jsonPath: .status.status.conditions[-1].type
      name: Status
      type: string
    - description: Ocid of the OciSecurityList
      jsonPath: .status.status.ocid
      name: Ocid
      priority: 1
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: OciSecurityList is the Schema for the ocisecuritylists API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: OciSecurityListSpec defines the desired state of OciSecurityList
            properties:
              compartmentId:
                description: CompartmentId is the OCID of the compartment
                maxLength: 255
                minLength: 1
                type: string
              definedTags:
                additionalProperties:
                  additionalProperties:
                    type: string
                  type: object
                type: object
              displayName:
                description: DisplayName is a user-friendly name for the Security
                  List
                type: string
              egressSecurityRules:
                description: EgressSecurityRules are the egress rules
                items:
                  description: EgressSecurityRule defines an egress rule
                  properties:
                    description:
                      type: string
                    destination:
                      type: string
                    isStateless:
                      type: boolean
                    protocol:
                      type: string
                    tcpOptions:
                      description: TcpOptions for TCP rules
                      properties:
                        destinationPortRange:
                          description: PortRange defines min/max port
                          properties:
                            max:
                              type: integer
                            min:
                              type: integer
                          required:
                          - max
                          - min
                          type: object
                        sourcePortRange:
                          description: PortRange defines min/max port
                          properties:
                            max:
                              type: integer
                            min:
                              type: integer
                          required:
                          - max
                          - min
                          type: object
                      type: object
                    udpOptions:
                      description: UdpOptions for UDP rules
                      properties:
                        destinationPortRange:
                          description: PortRange defines min/max port
                          properties:
                            max:
                              type: integer
                            min:
                              type: integer
                          required:
                          - max
                          - min
                          type: object
                        sourcePortRange:
                          description: PortRange defines min/max port
                          properties:
                            max:
                              type: integer
                            min:
                              type: integer
                          required:
                          - max
                          - min
                          type: object
                      type: object
                  required:
                  - destination
                  - protocol
                  type: object
                type: array
              freeformTags:
                additionalProperties:
                  type: string
                type: object
              id:
                description: SecurityListId is the OCID of an existing Security List
                  to bind to (optional)
                maxLength: 255
                minLength: 1
                type: string
              ingressSecurityRules:
                description: IngressSecurityRules are the ingress rules
                items:
                  description: IngressSecurityRule defines an ingress rule for a security
                    list
                  properties:
                    description:
                      type: string
                    isStateless:
                      type: boolean
                    protocol:
                      type: string
                    source:
                      type: string
                    tcpOptions:
                      description: TcpOptions for TCP rules
                      properties:
                        destinationPortRange:
                          description: PortRange defines min/max port
                          properties:
                            max:
                              type: integer
                            min:
                              type: integer
                          required:
                          - max
                          - min
                          type: object
                        sourcePortRange:
                          description: PortRange defines min/max port
                          properties:
                            max:
                              type: integer
                            min:
                              type: integer
                          required:
                          - max
                          - min
                          type: object
                      type: object
                    udpOptions:
                      description: UdpOptions for UDP rules
                      properties:
                        destinationPortRange:
                          description: PortRange defines min/max port
                          properties:
                            max:
                              type: integer
                            min:
                              type: integer
                          required:
                          - max
                          - min
                          type: object
                        sourcePortRange:
                          description: PortRange defines min/max port
                          properties:
                            max:
                              type: integer
                            min:
                              type: integer
                          required:
                          - max
                          - min
                          type: object
                      type: object
                  required:
                  - protocol
                  - source
                  type: object
                type: array
              vcnId:
                description: VcnId is the OCID of the VCN that contains this Security
                  List
                maxLength: 255
                minLength: 1
                type: string
            required:
            - compartmentId
            - displayName
            - vcnId
            type: object
          status:
            description: OciSecurityListStatus defines the observed state of OciSecurityList
            properties:
              status:
                properties:
                  conditions:
                    items:
                      properties:
                        lastTransitionTime:
                          format: date-time
                          type: string
                        message:
                          type: string
                        reason:
                          type: string
                        status:
                          type: string
                        type:
                          type: string
                      required:
                      - status
                      - type
                      type: object
                    type: array
                  createdAt:
                    format: date-time
                    type: string
                  deletedAt:
                    format: date-time
                    type: string
                  message:
                    type: string
                  ocid:
                    maxLength: 255
                    minLength: 1
                    type: string
                  reason:
                    type: string
                  requestedAt:
                    format: date-time
                    type: string
                  updatedAt:
                    format: date-time
                    type: string
                type: object
            required:
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
