---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: opensearchclusters.oci.oracle.com
spec:
  group: oci.oracle.com
  names:
    kind: OpenSearchCluster
    listKind: OpenSearchClusterList
    plural: opensearchclusters
    singular: opensearchcluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.displayName
      name: DisplayName
      priority: 1
      type: string
    - description: status of the OpenSearchCluster
      jsonPath: .status.status.conditions[-1].type
      name: Status
      type: string
    - description: Ocid of the OpenSearchCluster
      jsonPath: .status.status.ocid
      name: Ocid
      priority: 1
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: OpenSearchCluster is the Schema for the opensearchclusters API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OpenSearchClusterSpec defines the desired state of OpenSearchCluster
            properties:
              compartmentId:
                description: The OCID of the compartment in which to create the cluster
                maxLength: 255
                minLength: 1
                type: string
              dataNodeCount:
                description: The number of data nodes
                minimum: 1
                type: integer
              dataNodeHostBareMetalShape:
                description: The bare metal shape for data nodes
                type: string
              dataNodeHostMemoryGB:
                description: Memory in GB per data node
                minimum: 1
                type: integer
              dataNodeHostOcpuCount:
                description: OCPUs per data node
                minimum: 1
                type: integer
              dataNodeHostType:
                description: The instance type for data nodes
                enum:
                - FLEX
                - BM
                - DENSE_IO
                type: string
              dataNodeStorageGB:
                description: Storage in GB per data node
                minimum: 1
                type: integer
              definedTags:
                additionalProperties:
                  additionalProperties:
                    type: string
                  type: object
                type: object
              displayName:
                description: The display name of the cluster
                type: string
              freeformTags:
                additionalProperties:
                  type: string
                type: object
              id:
                description: The OCID of an existing OpenSearch cluster to bind
                maxLength: 255
                minLength: 1
                type: string
              masterNodeCount:
                description: The number of master nodes
                minimum: 1
                type: integer
              masterNodeHostBareMetalShape:
                description: The bare metal shape for master nodes
                type: string
              masterNodeHostMemoryGB:
                description: Memory in GB per master node
                minimum: 1
                type: integer
              masterNodeHostOcpuCount:
                description: OCPUs per master node
                minimum: 1
                type: integer
              masterNodeHostType:
                description: The instance type for master nodes
                enum:
                - FLEX
                - BM
                type: string
              opendashboardNodeCount:
                description: The number of OpenSearch Dashboard nodes
                minimum: 1
                type: integer
              opendashboardNodeHostMemoryGB:
                description: Memory in GB for dashboard nodes
                minimum: 1
                type: integer
              opendashboardNodeHostOcpuCount:
                description: OCPUs for dashboard nodes
                minimum: 1
                type: integer
              securityMasterUserName:
                description: The name of the master user for security config
                type: string
              securityMasterUserPasswordHash:
                description: The password hash of the master user for security config
                type: string
              securityMode:
                description: The security mode of the cluster
                enum:
                - DISABLED
                - PERMISSIVE
                - ENFORCING
                type: string
              softwareVersion:
                description: The version of OpenSearch software to run
                type: string
              subnetCompartmentId:
                description: The OCID of the compartment where the subnet is located
                maxLength: 255
                minLength: 1
                type: string
              subnetId:
                description: The OCID of the subnet
                maxLength: 255
                minLength: 1
                type: string
              vcnCompartmentId:
                description: The OCID of the compartment where the VCN is located
                maxLength: 255
                minLength: 1
                type: string
              vcnId:
                description: The OCID of the VCN
                maxLength: 255
                minLength: 1
                type: string
            type: object
          status:
            description: OpenSearchClusterStatus defines the observed state of OpenSearchCluster
            properties:
              status:
                properties:
                  conditions:
                    items:
                      properties:
                        lastTransitionTime:
                          format: date-time
                          type: string
                        message:
                          type: string
                        reason:
                          type: string
                        status:
                          type: string
                        type:
                          type: string
                      required:
                      - status
                      - type
                      type: object
                    type: array
                  createdAt:
                    format: date-time
                    type: string
                  deletedAt:
                    format: date-time
                    type: string
                  message:
                    type: string
                  ocid:
                    maxLength: 255
                    minLength: 1
                    type: string
                  reason:
                    type: string
                  requestedAt:
                    format: date-time
                    type: string
                  updatedAt:
                    format: date-time
                    type: string
                type: object
            required:
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
