
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: redisclusters.oci.oracle.com
spec:
  group: oci.oracle.com
  names:
    kind: RedisCluster
    listKind: RedisClusterList
    plural: redisclusters
    singular: rediscluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.displayName
      name: DisplayName
      priority: 1
      type: string
    - description: status of the RedisCluster
      jsonPath: .status.status.conditions[-1].type
      name: Status
      type: string
    - description: Ocid of the RedisCluster
      jsonPath: .status.status.ocid
      name: Ocid
      priority: 1
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: RedisCluster is the Schema for the redisclusters API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RedisClusterSpec defines the desired state of RedisCluster
            properties:
              Id:
                description: RedisClusterId is the OCID of an existing Redis cluster
                  to bind. If empty, a new cluster will be created.
                maxLength: 255
                type: string
              compartmentId:
                description: CompartmentId is the OCID of the compartment that contains
                  the Redis cluster.
                maxLength: 255
                type: string
              definedTags:
                additionalProperties:
                  additionalProperties:
                    type: string
                  type: object
                description: DefinedTags for the resource.
                type: object
              displayName:
                description: DisplayName is a user-friendly name for the Redis cluster.
                type: string
              freeformTags:
                additionalProperties:
                  type: string
                description: FreeFormTags for the resource.
                type: object
              nodeCount:
                description: NodeCount is the number of nodes in the Redis cluster.
                minimum: 1
                type: integer
              nodeMemoryInGBs:
                description: NodeMemoryInGBs is the amount of memory allocated to
                  the Redis cluster's nodes, in gigabytes.
                minimum: 1
                type: number
              softwareVersion:
                description: SoftwareVersion is the Redis version that the cluster
                  is running.
                enum:
                - V7_0_5
                type: string
              subnetId:
                description: SubnetId is the OCID of the Redis cluster's subnet.
                maxLength: 255
                type: string
            required:
            - compartmentId
            - displayName
            - nodeCount
            - nodeMemoryInGBs
            - softwareVersion
            - subnetId
            type: object
          status:
            description: RedisClusterStatus defines the observed state of RedisCluster
            properties:
              status:
                description: OSOKStatus defines the observed state of a provisioned
                  resource
                properties:
                  conditions:
                    items:
                      description: OSOKCondition defines the condition for the resource
                      properties:
                        lastTransitionTime:
                          format: date-time
                          type: string
                        message:
                          type: string
                        reason:
                          type: string
                        resourceVersion:
                          type: string
                        status:
                          type: string
                        type:
                          description: OSOKStatusCondition defines the condition type
                            for the resource
                          type: string
                      required:
                      - status
                      - type
                      type: object
                    type: array
                  createdAt:
                    format: date-time
                    type: string
                  deletedAt:
                    format: date-time
                    type: string
                  message:
                    type: string
                  ocid:
                    maxLength: 255
                    type: string
                  updatedAt:
                    format: date-time
                    type: string
                type: object
            required:
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
