---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.3
  name: ociqueues.oci.oracle.com
spec:
  group: oci.oracle.com
  names:
    kind: OciQueue
    listKind: OciQueueList
    plural: ociqueues
    singular: ociqueue
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.displayName
      name: DisplayName
      priority: 1
      type: string
    - description: status of the OciQueue
      jsonPath: .status.status.conditions[-1].type
      name: Status
      type: string
    - description: Ocid of the OciQueue
      jsonPath: .status.status.ocid
      name: Ocid
      priority: 1
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: OciQueue is the Schema for the ociqueues API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: OciQueueSpec defines the desired state of OciQueue
            properties:
              compartmentId:
                description: CompartmentId is the OCID of the compartment in which
                  to create the Queue
                maxLength: 255
                minLength: 1
                type: string
              customEncryptionKeyId:
                description: CustomEncryptionKeyId is the OCID of the custom encryption
                  key for message content (optional)
                maxLength: 255
                minLength: 1
                type: string
              deadLetterQueueDeliveryCount:
                description: |-
                  DeadLetterQueueDeliveryCount is the number of times a message can be delivered before being moved to the DLQ
                  A value of 0 disables the DLQ
                minimum: 0
                type: integer
              definedTags:
                additionalProperties:
                  additionalProperties:
                    type: string
                  type: object
                type: object
              displayName:
                description: DisplayName is a user-friendly name for the Queue
                type: string
              freeformTags:
                additionalProperties:
                  type: string
                type: object
              id:
                description: The OCID of an existing Queue to bind to (optional; if
                  omitted, a new queue is created)
                maxLength: 255
                minLength: 1
                type: string
              retentionInSeconds:
                description: RetentionInSeconds is the retention period of messages
                  in the queue, in seconds
                minimum: 10
                type: integer
              timeoutInSeconds:
                description: TimeoutInSeconds is the default polling timeout of messages
                  in the queue, in seconds
                minimum: 1
                type: integer
              visibilityInSeconds:
                description: VisibilityInSeconds is the default visibility timeout
                  of messages consumed from the queue, in seconds
                minimum: 1
                type: integer
            required:
            - compartmentId
            - displayName
            type: object
          status:
            description: OciQueueStatus defines the observed state of OciQueue
            properties:
              status:
                properties:
                  conditions:
                    items:
                      properties:
                        lastTransitionTime:
                          format: date-time
                          type: string
                        message:
                          type: string
                        reason:
                          type: string
                        status:
                          type: string
                        type:
                          type: string
                      required:
                      - status
                      - type
                      type: object
                    type: array
                  createdAt:
                    format: date-time
                    type: string
                  deletedAt:
                    format: date-time
                    type: string
                  message:
                    type: string
                  ocid:
                    maxLength: 255
                    minLength: 1
                    type: string
                  reason:
                    type: string
                  requestedAt:
                    format: date-time
                    type: string
                  updatedAt:
                    format: date-time
                    type: string
                type: object
            required:
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
